# Generated by Django 3.1.3 on 2020-11-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date_note',
            new_name='post_date_note',
        ),
    ]
