# Generated by Django 3.1.7 on 2021-04-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210413_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_note'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterField(
            model_name='note',
            name='category_note',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='notes.category', verbose_name='категория'),
        ),
        migrations.AlterField(
            model_name='note',
            name='content_note',
            field=models.TextField(blank=True, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='note',
            name='date_note',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title_note',
            field=models.CharField(blank=True, max_length=150, verbose_name='Заголовок'),
        ),
    ]
