# Generated by Django 3.1.3 on 2020-11-23 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201116_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='post_date_note',
        ),
    ]
